apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namePrefix: development-

patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 2048M
    target:
      kind: VirtualMachine
  - patch: |
      - op: replace
        path: /spec/to/name
        value: development-quotes-frontend
    target:
      kind: Route
      name: quotes-frontend
  - patch: |
      - op: replace
        path: /spec/to/name
        value: development-headless-service-backend
    target:
      kind: Route
      name: route-backend
  - patch: |
      - op: replace
        path: /spec/selector/vm.kubevirt.io~1name
        value: development-rhel9-quotes-backend
    target:
      kind: Service
      name: headless-service-backend
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: |
          URL=$(oc get route development-route-backend -o jsonpath='{.status.url}');
          oc create configmap environment-variables --from-literal=VITE_BACKEND_URL="$URL/quote" --dry-run=client -o yaml | oc apply -f -
    target:
      kind: Job
      name: configmap-pre-hook