apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-vm
spec:
  generators:
  - list:
      elements:
        - name: dev
          env: dev
          server: https://kubernetes.default.svc
        - name: prod
          env: prod
          server: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{name}}-demo-vm"
    spec:
      project: default
      source:
        repoURL: https://github.com/ignaciolago/gitops-demo.git
        targetRevision: HEAD
        path: "applicationsets/demo-vm/kustomize/{{env}}"
        kustomize:
          commonAnnotations:
            managed-cluster: "{{name}}"
      destination:
        server: "{{server}}"
        namespace: "{{name}}-demo-vm"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
