apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namePrefix: frontend-

patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 2048M
    target:
      kind: VirtualMachine
  - patch: |
      - op: replace
        path: /spec/ports/0/port
        value: 8080
    target:
      kind: Service
      name: headless-service
  - patch: |
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8080
    target:
      kind: Service
      name: headless-service
  - patch: |
      - op: replace
        path: /metadata/name
        value: frontend-service
    target:
      kind: Service
      name: headless-service