apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namePrefix: production-

patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 2048M
    target:
      kind: VirtualMachine
  - patch: |
      - op: replace
        path: /spec/to/name
        value: production-quotes-frontend
    target:
      kind: Route
      name: quotes-frontend
  - patch: |
      - op: replace
        path: /spec/to/name
        value: production-headless-service-backend
    target:
      kind: Route
      name: route-backend