apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00_virtualmachine.yaml
  - 01_node-frontend-configmap.yaml
  - 02_node-frontend-deployment.yaml
  - 03_node-frontend-service.yaml
  - 04_node-route.yaml